Module7 task1
htmlacademy-univer-javascript-1/2434203-kekstagram-4 pull request #7
Opened 2023-11-29 13:53 UTC by shndr1xa

2023-11-29 15:08 UTC, MaksimovG requested changes

2023-11-29 15:08 UTC, MaksimovG commented on js/miniPhotos.js
> +  const photosCollection = getPhotosArray(25);
магическое число

2023-11-30 15:17 UTC, MaksimovG requested changes

2023-11-30 15:17 UTC, MaksimovG commented on js/miniPhotos.js
> +  const photosCollection = getPhotosArray(photosCount);
такое ощущение буд-то не смотрели лекцию. Я в нескольких лекция говорил и показывал: данные передаются из main. Мы не создаем данные внутри модулей. Мы создали их в самом верху кода - в точке входа - файл main и дальше передаем их как параметры функции. Решение этой домашки вообще было полностью дано. И еще и показано как в дальнейшем вытащить и другие нужные данные не экспортируя их

2023-12-02 17:17 UTC, MaksimovG requested changes

2023-12-02 17:17 UTC, MaksimovG commented on js/miniPhotos.js
> +import { getPhotosArray } from './utils.js';
файлы называются через дефис

2023-12-02 17:17 UTC, MaksimovG commented on js/main.js
> +const picContainer = document.querySelector('.pictures');
Контейнер находится внутри модуля отвечающего за отрисовку pictures. то есть в mini-photos

2023-12-02 17:17 UTC, MaksimovG commented on js/miniPhotos.js
> +  const photosCollection = getPhotosArray(photosCount);
проигнорированный комментарий

2023-12-02 17:17 UTC, MaksimovG commented on js/data.js
> +export const photosCount = 25;
это константа.
ПЕРЕЧИТЫВАЕМ КРИТЕРИИ

2023-12-02 17:17 UTC, MaksimovG commented on js/main.js
> +const picTemp = document.querySelector('#picture').content.querySelector('.picture');
невнятное название - опять в критерии

2023-12-02 17:17 UTC, MaksimovG commented on js/utils.js
>     return photo;
getPhotosArray = () => Array.from({length: COUNT_PHOTO}, photoExample);

2023-12-02 17:17 UTC, MaksimovG commented on js/utils.js
>     const photo = Array.from({length: COUNT_PHOTO}, photoExample);
getPhotoExample - опять критерии

2023-12-02 17:17 UTC, MaksimovG commented on js/data.js
> +export const photosCount = 25;
Тем более ниже в коде она уже есть

2023-12-02 20:10 UTC, shndr1xa commented on js/miniPhotos.js
> +import { getPhotosArray } from './utils.js';
utils это одно слово, куда здесь дефисы я должен ставить?

2023-12-02 20:17 UTC, shndr1xa commented on js/main.js
> +const picContainer = document.querySelector('.pictures');
Вы же мне сказали все данные перенести в main.js, я не могу сделать задания до дедлайна, тк вы противоречите своим же требованиям

2023-12-03 14:59 UTC, MaksimovG requested changes

2023-12-03 14:59 UTC, MaksimovG commented on js/main.js
> +createMiniPhotos(pictureTemplate, photosCollection)
почему pictureTemplate не находится внутри функции createMiniPhotos. Так же переименовать с create на render. Эта функция отрисовывает, а не создает миниатюры.

2023-12-03 14:59 UTC, MaksimovG commented on js/utils.js
>     comments: Array.from({length:getRandomInteger(0 , COMMENTS_MAX)}, commentExample)
а commentExample почему не переимновали

2023-12-04 09:41 UTC, MaksimovG requested changes

2023-12-04 09:41 UTC, MaksimovG commented on js/utils.js
>     comments: Array.from({length:getRandomInteger(0 , COMMENTS_MAX)}, commentExample)
А проигнорировали почему, не вижу изменений

2023-12-04 09:41 UTC, MaksimovG commented on js/utils.js
>  const commentExample = () => ({
Как должны называться функции?

2023-12-07 07:02 UTC, MaksimovG approved these changes

2023-12-07 07:02 UTC, merged